"use strict";
let integerNumber = 0;
let integer_number = 1;
let IntegerNumber = 2;
alert(integerNumber);
console.log(integerNumber);
alert(integer_number);
console.log(integer_number);
alert(IntegerNumber);
console.log(IntegerNumber);